### ISSUE TITLE
Is letting webanimations-js modify the DOM a React way of doing things?

### ISSUE THREAD

**Issue by lukebatchelor** [bringking/react-web-animation#30]
Hi, we were just evaluating your library for use in a project. We were looking for something that does exactly this, but I'm just wondering how you get around the issue of manipulating the DOM outside of React. 

Typically this would be considered bad practice right? If the component you were animating were to re-render and be setting its own inline styles during that render, would you not have issues with styles getting overwritten?

I'm slightly confused though, because in practice, the animation overwrites any style props that it is modifying (doesn't change any other ones). Setting the fill mode to 'none' removes the issue of losing conflicting styles at the end, but it still feels strange to be letting the DOM be manipulated outside of React.

I've had a quick look through the source and can't see any sort of magic like that described by ryanflorence here (https://github.com/ryanflorence/react-training/blob/gh-pages/lessons/05-wrapping-dom-libs.md). 

Just wondering if I'm missing something here.

Cheers

**Comment by bringking** [comment]
@lukebatchelor This is a really great point and because this library wraps the web animations polyfill, you do need to consider this behavior slightly. You are not missing anything, but here is how I handle it - 

## Chrome and Opera

For Chrome, the exposed methods in this library (like GroupEffects and SequenceEffects) work directly on the DOM API and don't modify the inline styles, so this is the intended behavior. Setting inline styles on the elements or modifying the DOM nodes would work in tandem with the browsers default behavior 

## Other Browsers

In this case, the web animations polyfill falls back to using inline styles (documented [here](https://github.com/web-animations/web-animations-js#caveats)), so in this case, any React set or passed inline style to that component will be overwritten by the polyfill. To work with this you can- 
- Apply custom styles to the element as normal, keeping in mind that the polyfill will replace them as necessary during an animation.
- Allow custom styles to be applied to the component, but merge them with your defined keyframes, so you can be sure they are always set. Changing the keyframes (or styles in this case) in the middle of the animation will currently force the animation to restart.
- This is kind of a non-option, but you could just not inline styles in conjunction with this library, use class based modifications if necessary 

It would be interesting to take a React first approach and re-implement the polyfill so that it works with React directly, but I don't think that is in the roadmap for this library. I hope this helps. If you have any ideas or changes we can make, let me know!

**Comment by lukebatchelor** [comment]
@bringking Thanks for the super prompt response.
Regarding point 2, I actually attempted a [quick spike](http://jsbin.com/duwunec/edit?html,js,output) of that last night

It's barebones but can combine styles, including complicated combines like transform and box-shadow.
I'll clean it up, flesh out the rest of the functionality and publish it at some point

I was thinking this could solve most of the use cases, any time where the inline styles aren't changing at the same as the animation is running. This _combined_ with the [roadmap](https://github.com/RinconStrategies/react-web-animation/blob/master/ROADMAP.md) item to allow hot keyframe replacement would be absolutely perfect I think. 

(Well, not perfect, it would be much nicer to not have to include a whole bunch non-changing styles getting applied via the webanimation, and should do the job until it is native)

**Comment by bringking** [comment]
@lukebatchelor Your spike looks great! I will work on the hot-keyframe roadmap item as my next task to help this along. Quick question about the spike - If you are working in React, how common will it be to have to extract a `cssText` (in your code `styleStringToJson(elem.style.cssText);`) from an element? Do you have a need for this in your use case? I haven't run into a scenario where I need to do that, unless I am reaching out into the DOM outside of React.

**Comment by lukebatchelor** [comment]
@bringking RE: `cssText`, Yea, wouldn't use that in react, you would always have a JSON representation of the styles in the React component, it was just useful for the demo. 

I'll probably have the `styleStringToJson()` method exposed though in case someone wanted to pull styles from a non React component.
