### ISSUE TITLE
Errors when rebuilding the project

### ISSUE THREAD

**Issue by laaglu** [bringking/react-web-animation#41]
I am trying to rebuild react-web-animation to write a patch but I get errors when I run npm install:

```
ERROR in ./src/animation.js
Module not found: Error: Cannot resolve module 'immutable' in /home/laaglu/git/forked/react-web-animation/src
 @ ./src/animation.js 13:17-37
```

Indeed, the package.json declares 'immutable' as a peer dependency. Shouldn't 'immutable' be declared as a regular dependency as is it actually used by the code, notably in Animation.js ?
`import { Map, is } from 'immutable';`

I tried that and it seemed to fix the problem for me.

**Comment by bringking** [comment]
@laaglu generally I tried to stick the commonly used packages (react, react-dom and immutable) as peer dependencies. In that way, I don't force you to install two versions of immutable and you can bring your own when you use this library. It works in the same way the react peer dependency works. I think we can remove the dependency entirely, since it is barely used and replace it with a simple deep check by lodash or something similar.

**Comment by laaglu** [comment]
Would you like me to prepare a pull request which would change Animation.js to remove the dependency on immutable ?

**Comment by bringking** [comment]
@laaglu for sure! If you want to tackle it, that would be awesome

**Comment by bringking** [comment]
This is rendered OBE by https://github.com/bringking/react-web-animation/pull/43. Closing
